txt_to_beep = {
    # Letters
    'A': 'bop beep boop',
    'B': 'bop boop beep beep beep',
    'C': 'bop boop beep boop beep',
    'D': 'bop boop beep beep',
    'E': 'bop beep',
    'F': 'bop beep beep boop beep',
    'G': 'bop boop boop beep',
    'H': 'bop beep beep beep beep',
    'I': 'bop beep beep',
    'J': 'bop beep boop boop boop',
    'K': 'bop boop beep boop',
    'L': 'bop beep boop beep beep',
    'M': 'bop boop boop',
    'N': 'bop boop beep',
    'O': 'bop boop boop boop',
    'P': 'bop beep boop boop beep',
    'Q': 'bop boop boop beeb boop',
    'R': 'bop beep boop beep',
    'S': 'bop beep beep beep',
    'T': 'bop boop',
    'U': 'bop beep beep boop',
    'V': 'bop beep beep beep boop',
    'W': 'bop beep boop boop',
    'X': 'bop boop beep beep boop',
    'Y': 'bop boop beep boop boop',
    'Z': 'bop boop boop beep beep',
    'a': 'beep boop',
    'b': 'boop beep beep beep',
    'c': 'boop beep boop beep',
    'd': 'boop beep beep',
    'e': 'beep',
    'f': 'beep beep boop beep',
    'g': 'boop boop beep',
    'h': 'beep beep beep beep',
    'i': 'beep beep',
    'j': 'beep boop boop boop',
    'k': 'boop beep boop',
    'l': 'beep boop beep beep',
    'm': 'boop boop',
    'n': 'boop beep',
    'o': 'boop boop boop',
    'p': 'beep boop boop beep',
    'q': 'boop boop beeb boop',
    'r': 'beep boop beep',
    's': 'beep beep beep',
    't': 'boop',
    'u': 'beep beep boop',
    'v': 'beep beep beep boop',
    'w': 'beep boop boop',
    'x': 'boop beep beep boop',
    'y': 'boop beep boop boop',
    'z': 'boop boop beep beep',
    # Numbers
    '0': 'boop boop boop boop boop',
    '1': 'beep boop boop boop boop',
    '2': 'beep beep boop boop boop',
    '3': 'beep beep beep boop boop',
    '4': 'beep beep beep beep boop',
    '5': 'beep beep beep beep beep',
    '6': 'boop beep beep beep beep',
    '7': 'boop boop beep beep beep',
    '8': 'boop boop boop beep beep',
    '9': 'boop boop boop boop beep',
    # Tokens
    '{': 'beep bop',
    '}': 'boop bop',
    '[': 'beep beep bop',
    ']': 'boop boop bop',
    '(': 'boop beep bop',
    ')': 'beep boop bop',
    '.': 'bop beep bop',
    ',': 'bop boop bop',
    ';': 'beep bop beep',
    ':': 'boop bop boop',
    '|': '~//',
}